#!/bin/bash
versao="1.0"
clear
echo "======================================================="
echo "Patch Brasileiro HelpDesk"
echo "Autor Felipe Lyrio - Empresa HelpDesk Inova"
echo "https://www.helpdeskinova.com.br / 021 99071-4087"
echo "======================================================="
echo ""
sleep 10
echo ""
echo "INICIANDO O PROCESSO..."
echo ""
echo "Atualizando o sistema OS..."
echo ""
#yum -y update && yum -y upgrade
echo ""
echo "Instando sshpass"
echo ""
#yum install sshpass
echo ""
echo "Instalando audio em Português Brasil"
echo ""
rsync --progress -r -u /usr/src/voiphelpdeskinova/audio/ /var/lib/asterisk/sounds/
sed -i '/language=pt_BR/d' /etc/asterisk/sip_general_custom.conf
echo "language=pt_BR" >> /etc/asterisk/sip_general_custom.conf
sed -i '/language=pt_BR/d' /etc/asterisk/iax_general_custom.conf
echo "language=pt_BR" >> /etc/asterisk/iax_general_custom.conf
sed -i '/defaultlanguage=pt_BR/d' /etc/asterisk/asterisk.conf
echo "defaultlanguage=pt_BR" >> /etc/asterisk/asterisk.conf
echo ""
sleep 10 
cd -f -r https://www.helpdeskinova.com.br/pabx/imag/helpdeskinova_logo_mini.png/ /var/www/html/themes/tenant/images
cd -f -r https://www.helpdeskinova.com.br/pabx/imag/helpdeskinova_logo_mini2.png/ /var/www/html/themes/tenant/images
sleep 10
#echo Instalando codec g729
#echo yum install asterisk-codec-g729 -y
#echo ""
echo ""
sleep 10
echo "Instalando sngrep"
echo "" 
rm -Rf /etc/yum.repos.d/irontec.repo
cat > /etc/yum.repos.d/irontec.repo <<EOF
[irontec]
name=Irontec RPMs repository
baseurl=http://packages.irontec.com/centos/\$releasever/\$basearch/
EOF
rpm --import http://packages.irontec.com/public.key
yum install sngrep -y
echo ""
wget https://bintray.com/ookla/rhel/rpm -O /etc/yum.repos.d/bintray-ookla-rhel.repo
yum install speedtest -y
wget -O /usr/bin/speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x /usr/bin/speedtest-cli
sleep 10
echo "REMOVENDO CADASTRO TELA INDEX"
echo ""
sed -i '/neo-modal-issabel-popup-box/d' /var/www/html/themes/tenant/_common/index.tpl
sed -i '/neo-modal-issabel-popup-title/d' /var/www/html/themes/tenant/_common/index.tpl
sed -i '/neo-modal-issabel-popup-close/d' /var/www/html/themes/tenant/_common/index.tpl
sed -i '/neo-modal-issabel-popup-content/d' /var/www/html/themes/tenant/_common/index.tpl
sed -i '/neo-modal-issabel-popup-blockmask/d' /var/www/html/themes/tenant/_common/index.tpl
echo ""
echo "ALTERANDO MUSICONHOLD AGENTS"
echo ""
sed -i -r 's/;musiconhold=default/musiconhold=none/' /etc/asterisk/agents.conf
rm -Rf /usr/src/IssabelBR
amportal restart
echo "Patch Brasileiro para Issabel"
echo "Autor Felipe Lyrio - Empresa HelpDesk Inova"
echo "https://www.helpdeskinova.com.br / 021 99071-4087"
echo "======================================================="
echo ""
echo "Patch Brasileiro Instalado."
echo "Obrigado!"
echo ""
echo "** RECOMENDADO REINICIAR O SERVIDOR PARA EXECUTAR NOVO KERNEL E NOVO DAHDI **"
echo ""
